# Generated by Django 5.0.8 on 2024-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('subject', models.TextField(max_length=255)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
